server:
  port: 8080

spring:
  application:
    name: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: vanikumari.gulla2@gmail.com
    password: sbdroggzjfompwkp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    root: INFO
    org.springframework.mail: DEBUG
