server:
  port: 8761

spring:
  application:
    name: main-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
