server:
  port: 8081

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/productdata

  zipkin:
    base-url: http://localhost:9411/api/v2/spans
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

message: "Hello from Config Server for ProductService"
