server:
  port: 8081

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/productdata

  zipkin:
    base-url: http://localhost:9411
    enabled: true

  sleuth:
    sampler:
      probability: 1.0  # Trace 100% of requests (for dev); use 0.1 in production

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

message: "Welcome to Product Service"
