server:
  port: 8081

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdata

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true

message: "Welcome to Product Service"
