server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.app.productservice: DEBUG

resilience4j:
  retry:
    instances:
      emailServiceRetry:
        maxAttempts: 3
        waitDuration: 2s

  circuitbreaker:
    instances:
      emailServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
