server:
  port: 8081

spring:
  application:
    name: Product

  datasource:
    url: jdbc:mysql://localhost:3306/productsdata
    username: root
    password: root

  data:
    mongodb:
      uri: mongodb://localhost:27017/product_mongo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

resilience4j:
  circuitbreaker:
    instances:
      emailServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      emailServiceRetry:
        max-attempts: 3
        wait-duration: 2s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
