server:
  port: 8081

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/productdata

  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

message: "Welcome to Product Service"
