server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdata
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
