server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/usersdata
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  zipkin:
    base-url: http://localhost:9411
    enabled: true

  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 3               # Small window to trigger open state faster
        minimumNumberOfCalls: 3           # Start evaluating after 3 calls
        failureRateThreshold: 50          # If 2/3 fail => opens circuit
        waitDurationInOpenState: 10s      # Stay open for 10 seconds

  retry:
    instances:
      productService:
        max-attempts: 2                   # 1 main call + 1 retry
        wait-duration: 1s

message: "Hello from Config Server for UserService"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0
