server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdata
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  retry:
    instances:
      productService:
        max-attempts: 2
        wait-duration: 1s

message: "Hello from Config Server for UserService"
