server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/usersdata
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    tracing-library: brave
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

resilience4j:
  circuitbreaker:
    instances:
      productService:  # your Feign client or RestTemplate call name
        registerHealthIndicator: true
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  retry:
    instances:
      productService:
        max-attempts: 2
        wait-duration: 1s

message: "Welcome from Config server"
